Fixed Desync issue for Neotanks and destroyed Pipeseams
DeamonHunter/AWBW-Replay-Player pull request #141
Opened 2024-02-29 12:42 UTC by Nabelon

The neotank desync was caused by 'FuelUsagePerTurn' being set to 1 instead of 0.

CP of destroyed pipeseams is basically undefined, so I removed them from the equality check for buildings. How AWBW handles them is inconsistent; in the LL games I checked, the following happens:

- The turn a seam is destroyed, its CP is set to the last value of the undestroyed seam.
- The turn after, its CP is set to 20 and keeps this value for the rest of the game.

However, in one of my test games (ID: 1121885), the CP is set to 20 in the turn the seam is destroyed.

2024-02-29 14:30 UTC, Nabelon commented
Im not really happy with my solution to "fix" the pipe seam desync but when I asked in the discord why this weird behavior occurs i got no response. Adding code that sets destryoed pipe seams CP to 20 also seems kinda pointless, much easier to say CP is undefined and not check it when comparing pipe seams

2024-04-22 22:54 UTC, Nabelon commented
(I have no clue what the established convention for push requests is; it's my first time doing this, so feel free to comment if it should be done differently.)

Press enter to login: Just a minor issue I had using the app.

Added Clock: Go7 said something about it in the stream;. With the addition of live league, it feels like a good idea to add.
While writing the clock, I noticed that:
a) old code wasn't working as intended and always jumped into the "teams exist" condition (the team of a player is an integer in e.g. live league and not null).
b) Truncate=true doesn't work. Either that or the containers overlap. UIs are not my strong suit. I am unsure whether I should just ignore it or take a prefix of the player name.

2024-04-29 23:31 UTC, DeamonHunter requested changes
Sorry again for being so late at this. Looks good, just mainly has styling issues. If you run VS studio or Rider, I believe it should be able to pick up the styling for the project and apply it if you run Format File.

2024-04-29 23:31 UTC, DeamonHunter commented on AWBWApp.Game.Tests/Visual/Screens/TestScenePlayerDisplay.cs
> +            IBindable<bool> showClock;
```suggestion
    private IBindable<bool> showClock;
```

2024-04-29 23:31 UTC, DeamonHunter commented on AWBWApp.Game.Tests/Visual/Screens/TestScenePlayerDisplay.cs
> +            AddStep("Create Replay Player", () => reset(false, false,showClock));
```suggestion
            AddStep("Create Replay Player", () => reset(false, false, showClock));
```

2024-04-29 23:31 UTC, DeamonHunter commented on AWBWApp.Game/API/Replay/ReplayBuilding.cs
> +            if (TerrainID != 115 && TerrainID != 116 && Capture != other.Capture)
Might be best if these numbers were named constants like `pipe_seam` and `pipe_seam_destroyed`

2024-04-29 23:31 UTC, DeamonHunter commented on AWBWApp.Game/UI/Replay/ReplayPlayerListItem.cs
> +                    clock.Text = time .ToString(@"hh\:mm\:ss");
```suggestion
                    clock.Text = time.ToString(@"hh\:mm\:ss");
```

2024-04-29 23:31 UTC, DeamonHunter commented on AWBWApp.Game/UI/Replay/ReplayPlayerListItem.cs
> +                if(showClockValue.NewValue) {
{ on newlines

2024-04-30 08:56 UTC, merged