add visual setting to lock map position
DeamonHunter/AWBW-Replay-Player pull request #144
Opened 2024-07-29 21:33 UTC by rorosaurus

Using the existing hack from the Replay Carousel to implement a simple map lock feature, as I've often heard it requested by streamers/youtubers. 😄 

![image](https://github.com/user-attachments/assets/67f92075-acea-4baa-b36c-6ce1665eaec4)

I did some basic testing but I'm overriding all `OnScroll` and `OnDragStart` events in `CameraControllerWithGrid.cs`, and I'm not intimately familiar with this application in the first place. So a second pair of eyes to make sure I'm not suppressing something important would be nice!

2024-07-30 10:28 UTC, DeamonHunter requested changes
Looks pretty good. Just some styling issues then it should be mergeable.

2024-07-30 10:31 UTC, DeamonHunter requested changes
Sorry, didn't properly start the review.

2024-07-30 10:31 UTC, DeamonHunter commented on AWBWApp.Game/UI/CameraControllerWithGrid.cs
> +            {
Styling is that single line ifs don't have braces.

2024-07-30 10:31 UTC, DeamonHunter commented on AWBWApp.Game/UI/CameraControllerWithGrid.cs
> +        private Bindable<bool> lockMapPosition;
Should be an IBindable. IBindable means that it can't edit the underlining value, which is true in this case.

2024-07-30 21:38 UTC, rorosaurus commented
Requested changes added!

2024-07-31 11:11 UTC, merged

2024-07-31 11:12 UTC, DeamonHunter commented
I'll get a build out when I get the time. Thanks for doing this!